resource "tfe_variable_set" "tfe-ws-token-service" {
  name         = "tfe-ws-token-product-inventory"
  description  = "This variable set contains a Terraform Cloud token for self-configuration of workspaces in the \"services-meta\" projects."
  organization = local.tfe_organization
  workspace_ids = [
    local.service_meta_index_workspace_id,
    module.svc-ws-subscriptions.tfe_workspace_id,
  ]
}

resource "tfe_variable_set" "github_access_token" {
  name         = "github-access-token"
  description  = "This variable set contains a GitHub access token generated by the Github bot"
  organization = local.tfe_organization
  workspace_ids = [
    module.svc-ws-subscriptions.tfe_workspace_id,
  ]
}
